# Generated by Django 6.0.1 on 2026-01-14 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'hôtel")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par nuit')),
                ('devise', models.CharField(choices=[('XOF', 'F XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'db_table': 'hotels',
                'ordering': ['-created_at'],
            },
        ),
    ]
